on:
  push:
    branches:
      - $default-branch
    pull_request:
      - $default-branch

jobs:

  release:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: lein midje
      - name: release
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein with-profile deploy release
